### ISSUE TITLE
Plugin doesn't seem to work

### ISSUE THREAD

**Issue by stijink** [HackAttack/bamboo-github-status#1]
Hi,

i've installed the plugin on a server installation of bamboo 5.8.1.The github repository is a private one. I could not find any possibility to configure the plugin (it is enabled). Did i miss something ? Do i need to activate it per plan or repository ? :-)

**Comment by HackAttack** [comment]
There's no configuration, although there are some caveats that are not documented anywhere (which I'll fix):

1. It only works if there is exactly one repo associated with your plan, and it is a GitHub repo
2. The user associated with your repo (in Bamboo) in needs to have the ability to write commit statuses
3. It only works with github.com, not GitHub Enterprise

Can you search your Bamboo log for "GitHub" and see if there are any log statements or exceptions that might indicate what's going on?

**Comment by HackAttack** [comment]
Also, it's possible that I misinterpreted your issue. Are you saying the plugin doesn't work, or are you saying that, because there's no configuration for it, it's not clear whether it's active?
