### ISSUE TITLE
Adding default values fails when "XSRF Protection" is enabled

### ISSUE THREAD

**Issue by alindeman** [HackAttack/bamboo-github-status#12]
If "XSRF Protection" is enabled in Bamboo -> Configuration -> Security -> Security Settings, this plugin causes an error when viewing the Miscellaneous build config tab for the first time

```
java.lang.IllegalStateException: XSRF: A mutative operation was attempted on DefaultChain within a non-mutative HTTP request: https://bamboo.example/chain/admin/config/editChainMiscellaneous.action?buildKey=PDT-PJHM
```

It's not allowed to call mutative operations on GET requests (e.g., [savePlanAndDefinition](https://github.com/HackAttack/bamboo-github-status/blob/645ee8b1931a7700b9e4fb66ec0164b7df0ad485/src/main/java/com/mhackner/bamboo/Configuration.java#L58)) when XSRF Protection is enabled.

Is there a way to fix the bug that this code was intended to fix without mutating on a GET request?

**Comment by HackAttack** [comment]
Crap. I will release a new version that reverts this change, then investigate. This has been a tricky bug—working with the UI layer is not particularly intuitive.

**Comment by HackAttack** [comment]
Reverted the defective fix and reopened the original bug.
