### ISSUE TITLE
Support for Github Enterprise

### ISSUE THREAD

**Issue by rhoml** [HackAttack/bamboo-github-status#19]
We'd much like to use this plugin but we need to be able to configure the Github API url `ATLASSIAN_BAMBOO_GITHUB_API_BASE_URL` to use our internal Address. Do you think this is a feature that can be easily implemented?

**Comment by HackAttack** [comment]
This was implemented in #9.

**Comment by rhoml** [comment]
Oh thanks, I failed to read the code properly.

**Comment by rhoml** [comment]
I've been trying to make it work on bamboo 5.11.3 setting up `Datlassian.bamboo.github.api.base.url=https://xxx.com/api/v3` but I don't see the status showing up in Github PRs. Do I need to so any extra work?

**Comment by rhoml** [comment]
I found a problem within bamboo 5.11 and it can't connect properly using the github repository type. Will report it to atlassian
