### ISSUE TITLE
New Release that supports Bamboo 5.15.3 ?

### ISSUE THREAD

**Issue by stijink** [HackAttack/bamboo-github-status#23]
Hi,

i've just updated our bamboo version to 5.15.3. Coming with this update the plugin stopped working for us. Bamboo is telling me that the current version 1.6 of the plugin is incompatible. Is there a new release planned ?

**Comment by HackAttack** [comment]
1.7 released!

cc @RangerRick

**Comment by RangerRick** [comment]
Looks to be working here... Thanks!

**Comment by stijink** [comment]
@HackAttack Works like a charme. Thank you!
