### ISSUE TITLE
Is there a way to customize the message that appears on the status?

### ISSUE THREAD

**Issue by robreinert** [HackAttack/bamboo-github-status#3]
Hi, I appreciate your plugin.  

I was wondering if I can change the message that appears during various phases like pending, success, failure.  Currently it always says "default."  The link takes me to correct bamboo job, but if possible, I'd like to also display the bamboo build number on the message  (I think it is the description parameter on Github api).

![image](https://cloud.githubusercontent.com/assets/13420440/9751946/901ead46-5670-11e5-861b-6f37629916cf.png)

![image](https://cloud.githubusercontent.com/assets/13420440/9751960/b92717b4-5670-11e5-85ae-407431048a37.png)

**Comment by HackAttack** [comment]
Good idea. I will work on this and hopefully get it into the next release.

**Comment by robreinert** [comment]
Awesome!

**Comment by stijink** [comment]
+1

**Comment by HackAttack** [comment]
It will make sense to do this after or in conjunction with #8.

**Comment by robreinert** [comment]
Just upgraded to new version and looks great!  Thanks.

**Comment by HackAttack** [comment]
Cool, then I'm going to call this one fixed by #8. It's still not making use of the description parameter but I think having the stage map to the context is sufficient for most uses.
