### ISSUE TITLE
Is this somehow useable with Bamboo Cloud?

### ISSUE THREAD

**Issue by thenikso** [HackAttack/bamboo-github-status#4]
Hello, I tried to set this up on a Cloud instance and Bamboo comes back with:

```
The add-on at https://marketplace.atlassian.com/download/plugins/com.mhackner.bamboo-github-status/version/100100 cannot be installed on this OnDemand instance.
```

Given that I have a custom image, can I somehow install this plugin manually there and call it with a script action in Bamboo? 

Thanks!

**Comment by HackAttack** [comment]
Good question. I don't know how Bamboo Cloud works, or what is needed to make plugins compatible with it. Will have to investigate.

What do you mean by custom image? Do you have shell access to the VM? If so, maybe you could just download the JAR to the `plugins` directory and restart Bamboo?

**Comment by tedsteiner** [comment]
@thenikso If you figure out how to do this please let me know what you did. I've been trying to find a way to do this, as well.

**Comment by HackAttack** [comment]
As far as I can tell, it is not currently possible to write Bamboo plugins for cloud instances. Sorry :cry:
